export const LOAD_FIVE_DAY_FORECAST_SUCCESS = "LOAD_FIVE_DAY_FORECAST_SUCCESS";
export const LOAD_HOURLY_FORECASTS_SUCCESS = "LOAD_HOURLY_FORECASTS_SUCCESS";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_CURRENT_LOCATION_SUCCESS = "GET_CURRENT_LOCATION_SUCCESS";
export const CURRENT_LOCATION_UPDATED = "CURRENT_LOCATION_UPDATED";
export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";